version: '3'
services:
  mongo:
    image: mongo:3.0.15
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
  web:
    build: .
    command: yarn start
    tty: true
    volumes:
      - /src/node_modules
      - ./src:/src
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      NODE_ENV: "development"
    depends_on:
      - mongo
