version: '3'
services:
  web:
    build: .
    command: yarn start
    tty: true
    volumes:
      - /src/node_modules
      - ./src:/src
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      NODE_ENV: "development"